[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions."*"]
  node_bundler = "esbuild"
  timeout = 26
# Force Update Thu Apr 23 22:31:11 KST 2026
# Deploy Trigger: Fri Apr 24 12:53:39 KST 2026
# Deploy Trigger: Fri Apr 24 13:05:22 KST 2026
# Last Update: Fri Apr 24 13:09:42 KST 2026
# Last Deploy: Fri Apr 24 13:13:27 KST 2026
# Redeploy: Fri Apr 24 13:20:46 KST 2026
# Fix typo: Fri Apr 24 13:22:04 KST 2026
