[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions."*"]
  node_bundler = "esbuild"
  timeout = 26
# Force Update Thu Apr 23 22:31:11 KST 2026
